name: Fly deploy
on:
  push:
    paths: 
      - 'backend/**'
    branches:
      - main
env: 
    FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy Backend
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: | 
          flyctl auth login -t ${{ secrets.FLY_API_TOKEN }}
          flyctl deploy --remote-only --config=./backend/fly.toml
